development:
  adapter: postgresql
  encoding: unicode
  database: exampl
  pool: 2
  username: <%= ENV["username"] %>
  password: <%= ENV["password"] %>

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
